# this file is based on https://github.com/prometheus-operator/prometheus-operator/tree/main/test/framework/resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-tls
  namespace: example-monitoring-tls
  labels:
    app: sample-app-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-tls
  template:
    metadata:
      labels:
        app: sample-app-tls
    spec:
      containers:
        - name: sample-app-tls
          image: quay.io/coreos/instrumented-sample-app:0.2.0-bearer-mtls-1
          imagePullPolicy: IfNotPresent
          args:
            - --cert-path=/etc/certs
          ports:
            - name: web
              containerPort: 8080
            - name: mtls
              containerPort: 8081
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-certs
