kind: Service
apiVersion: v1
metadata:
  name: sample-app-tls
  namespace: example-monitoring-tls
  labels:
    app: sample-app-tls
spec:
  selector:
    app: sample-app-tls
  ports:
    - name: web
      port: 8080
    - name: mtls
      port: 8081
