apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app-tls
  namespace: example-monitoring-tls
spec:
  selector:
    matchLabels:
      app: sample-app-tls
  endpoints:
    - port: mtls
      interval: 30s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
        keySecret:
          name: tls-certs
          key: key.pem
        cert:
          secret:
            name: tls-certs
            key: cert.pem
