apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sc.example
  name: scrape-config-example-app
spec:
  containers:
  - image: ghcr.io/rhobs/prometheus-example-app:0.4.0
    name: example-app
    ports:
    # since /metrics is exposed in this port
    - containerPort: 8080
