apiVersion: v1
data:
  targets.yaml: |
    - labels:
        job: prometheus-operator
      targets:
      - prometheus-operator.default.svc.cluster.local:8080
    - labels:
        job: prometheus
      targets:
      - prometheus-operated.default.svc.cluster.local:9090
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: scrape-file-sd-targets
  namespace: default
