apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: scrape-config-static-config-example
  namespace: default
  labels:
    app.kubernetes.io/name: scrape-config-static-config-example
spec:
  staticConfigs:
    - labels:
        job: prometheus-operator
      targets:
      - prometheus-operator.default.svc.cluster.local:8080
    - labels:
        job: prometheus
      targets:
      - prometheus-operated.default.svc.cluster.local:9090
