apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: scrape-config-static-config-example
  namespace: default
  labels:
    app.kubernetes.io/name: scrape-config-static-config-example
spec:
  staticConfigs:
    - labels:
        job: alertmanager
      targets:
      - alertmanager-main.monitoring.svc.cluster.local:8080
    - labels:
        job: prometheus
      targets:
      - prometheus-k8s.monitoring.svc.cluster.local:9090
