apiVersion: v1
data:
  prometheus-additional-configs.yaml: ICMgZnJvbSBodHRwczovL2dpdGh1Yi5jb20vcHJvbWV0aGV1cy9wcm9tZXRoZXVzL2Jsb2IvYjM1NWU4MzNkNTYwZDdmZjhhZTE0NTNhYjM4N2E3YTY3NTg5YzJjNi9kb2N1bWVudGF0aW9uL2V4YW1wbGVzL3Byb21ldGhldXMta3ViZXJuZXRlcy55bWwjTDU5LUw4OQogIyBTY3JhcGUgY29uZmlnIGZvciBub2RlcyAoa3ViZWxldCkuCi0gam9iX25hbWU6ICJrdWJlcm5ldGVzLW5vZGVzIgogIHNjaGVtZTogaHR0cHMKICB0bHNfY29uZmlnOgogICAgICBjYV9maWxlOiAvdmFyL3J1bi9zZWNyZXRzL2t1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvY2EuY3J0CiAgICAgIGluc2VjdXJlX3NraXBfdmVyaWZ5OiB0cnVlCiAgYXV0aG9yaXphdGlvbjoKICAgICAgY3JlZGVudGlhbHNfZmlsZTogL3Zhci9ydW4vc2VjcmV0cy9rdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3Rva2VuCiAga3ViZXJuZXRlc19zZF9jb25maWdzOgogIC0gcm9sZTogbm9kZQogIHJlbGFiZWxfY29uZmlnczoKICAgIC0gYWN0aW9uOiBsYWJlbG1hcAogICAgICByZWdleDogX19tZXRhX2t1YmVybmV0ZXNfbm9kZV9sYWJlbF8oLispCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
