kind: Service
apiVersion: v1
metadata:
  name: prometheus-example-app
  namespace: default
  labels:
    app.kubernetes.io/name: prometheus-example-app
spec:
  selector:
    app.kubernetes.io/name: prometheus-example-app
  ports:
  - name: web
    port: 8080
